# Generated by Django 4.0.4 on 2022-04-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(related_name='+', to='criteria.criteria'),
        ),
    ]
